module.exports = [
  {
    slug: 'coletiv',
    name: "Coletiv",
    site: "https://www.coletiv.com",
    logo: require('@assets/partners/coletiv/logo-map.png'),
    address: "Avenida da França, 352 4050-276 Porto Portugal",
    latitude: 41.16132235902691,
    longitude: -8.627314607425252,
    social_facebook: "https://www.facebook.com/wearecoletiv",
    social_twitter: "https://twitter.com/coletivstudio",
    social_linkedin: "https://linkedin.com/company/coletiv",
  },
  {
    slug: 'basecone',
    name: "Basecone",
    site: "https://www.basecone.com",
    logo: require('@assets/partners/basecone/logo-map.png'),
    address: "Praça Bom Sucesso 131, Edifício Península, 4150-146 Porto",
    latitude: 41.15680920857158,
    longitude: -8.630009553960608,
    social_facebook: "https://www.facebook.com/baseconenv",
    social_twitter: "https://twitter.com/basecone",
    social_linkedin: "https://linkedin.com/company/basecone​",
  },
  {
    slug: 'newwork',
    name: "New Work",
    site: "https://www.new-work.se/en/",
    logo: require('@assets/partners/newwork/logo-map.png'),
    address: "Rua Sousa Aroso 991, 4450-291 Matosinhos, Portugal",
    latitude: 41.17819092495354,
    longitude: -8.678966853960608,
  },
  {
    slug: 'glazed',
    name: "Glazed",
    site: "https://www.glazed.dev",
    logo: require('@assets/partners/glazed/logo-map.png'),
    address: "Rua Mouzinho de Albuquerque, nº 744, 3º andar, 4450-203 Matosinhos, Portugal",
    latitude: 41.176205249730934,
    longitude: -8.686051,
    social_facebook: "https://www.facebook.com/glazedEliteDevelopers/",
    social_twitter: "https://twitter.com/glazedSolutions",
    social_linkedin: "https://www.linkedin.com/company/glazed-solutions/​",
  },
];
